### PR TITLE
Supports increment method

### PR DESCRIPTION
**Pull request by asamek**
I've added support for `increment` method.

### CODE REVIEW

**Comment by asamek** [comment]
Fixed.

**Comment by fwolf** [comment]
There are one more step, please merge these 2 commit to 1 by git rebase:

In command line mode, type command `git rebase -i 578703f`, then change first word(`pick`) of the line `pick 4a62f15 code style fix` to `fix`, then save quit, push to your repo.

I think you know why we need to do this, by now the commit are not in repo yet, so we should avoid to use commit to fix previous commit.

**Comment by asamek** [comment]
Understand. But I got an error during rebase. When I changed `pick` to `fix` I got sth like 'there is no `fix` command.'. So I used `fixup` command but when I tried to push to my repo I got `failed to push some refs to`, so I pulled and pushed and there is still 2 commits. Is it OK?

**Comment by fwolf** [comment]
`fix` equals `fixup`, but seems you fogot to `push --force` to overwrite your repo on github, I fogot to metion it too. So now your git history tree looks like: 



There are 2 ways to solve this:
1. You use `git reset --hard c635eca` to delete 2 old commit, or git rebase -i then just delete line d0a5366 and 4a62f15, then `git push -f` to overwrite your repo. There are only 1 commit to merge left.
2. I can pull your repo branch incrementSupport, and do git reset, then push to my master branch, then you can pull to your forked repo's master branch, and leave incrementSupport branch as it is.

I recommend the first way, get familer with git is always helpful.

**Comment by asamek** [comment]
Done. Could you check this out?

**Comment by fwolf** [comment]
Works prefectly, thanks !

**Pull request merged**
